version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'bluedb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '%23Potatoe2'
      MYSQL_ROOT_PASSWORD: '%23Potatoe2'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
