version: '3.1'

services:
  db:
    image: mariadb:11.1.3
    restart: always
    container_name: blue-guam-db
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${SQL_LOGIN}
      - MARIADB_PASSWORD=${SQL_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - db:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d:ro
    networks:
      - db

  # api:
  #   networks:
  #     - db

volumes:
  db:

networks:
  db:
  production_proxy-network:
    external: true


# version: '3.1'

# services:
#   db:
#     image: mariadb:10.5
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#     volumes:
#       - /my/own/datadir:/var/lib/mysql
#     ports:
#       - "3306:3306"
