-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 21:56:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(45) NULL,
  `numberElements` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activity_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Region_id` INT NOT NULL,
  `description_id` INT NOT NULL,
  `name_id` INT NOT NULL,
  `shortDescrip_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`, `name_id`),
  INDEX `fk_Activity_data_Region1_idx` (`Region_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_text1_idx` (`description_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_text2_idx` (`name_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_text3_idx` (`shortDescrip_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_type1_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_images1_idx` (`images_id` ASC) VISIBLE,
  INDEX `fk_Activity_data_user1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_data_Region1`
    FOREIGN KEY (`Region_id`)
    REFERENCES `mydb`.`Region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_text1`
    FOREIGN KEY (`description_id`)
    REFERENCES `mydb`.`text` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_text2`
    FOREIGN KEY (`name_id`)
    REFERENCES `mydb`.`text` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_text3`
    FOREIGN KEY (`shortDescrip_id`)
    REFERENCES `mydb`.`text` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `mydb`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_data_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity_versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activity_versions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Activities_GIS_id` INT NOT NULL,
  `timestamp` TIMESTAMP(1) NOT NULL,
  `Activity_data_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity_versions_Activities_GIS1_idx` (`Activities_GIS_id` ASC) VISIBLE,
  INDEX `fk_Activity_versions_Activity_data1_idx` (`Activity_data_id` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_versions_Activities_GIS1`
    FOREIGN KEY (`Activities_GIS_id`)
    REFERENCES `mydb`.`Activities_GIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_versions_Activity_data1`
    FOREIGN KEY (`Activity_data_id`)
    REFERENCES `mydb`.`Activity_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activities_GIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activities_GIS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `x_coordinate` INT NOT NULL,
  `y_coordinate` INT NOT NULL,
  `Activity_versions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activities_GIS_Activity_versions_idx` (`Activity_versions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_GIS_Activity_versions`
    FOREIGN KEY (`Activity_versions_id`)
    REFERENCES `mydb`.`Activity_versions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`translation` (
  `text_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `text` VARCHAR(4000) NULL,
  INDEX `fk_translation_text1_idx` (`text_id` ASC) VISIBLE,
  INDEX `fk_translation_language1_idx` (`language_id` ASC) VISIBLE,
  PRIMARY KEY (`text_id`, `language_id`),
  CONSTRAINT `fk_translation_text1`
    FOREIGN KEY (`text_id`)
    REFERENCES `mydb`.`text` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_translation_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `mydb`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
